/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "rmprgydhttgrbqxwursx"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtcHJneWRodHRncmJxeHd1cnN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ2OTM0ODUsImV4cCI6MjA4MDI2OTQ4NX0.TKtpCTRoZcIBBrtAQA9qX3xw829-EQb4vt9zQrMEHXg"
export const functionName = "kidspiration-api" // TODO: Update this if your function name is different