export const ZONES = [
  "Aba Zone",
  "Abeokuta Ministry Centre",
  "Abakaliki Zone",
  "Abuja Ministry Centre",
  "Abuja Zone 1",
  "Abuja Zone 2",
  "Accra Ghana Zone",
  "Australia Region",
  "Bauchi Sub Zone",
  "Benin  Zone 2",
  "Benin Zone 1",
  "BLW ASIA ZONE",
  "BLW Benin Republic Zone A",
  "BLW Benin Republic Zone B",
  "BLW Burkina Faso Zone",
  "BLW CAMEROON GROUP 3",
  "BLW CAMEROON ZONE B",
  "BLW Cameroon Zone A",
  "BLW Canada Zone",
  "BLW CONGO ZONE",
  "BLW Cyprus Group",
  "BLW DEMOCRATIC REPUBLIC OF CONGO ZONE",
  "BLW Europe Zone 1 DSP",
  "BLW GHANA SUBZONE C",
  "BLW GHANA SUBZONE D",
  "BLW GHANA SUBZONE E",
  "BLW GHANA SUBZONE F",
  "BLW GHANA ZONE A",
  "BLW GHANA ZONE B",
  "BLW Ghana Zone C",
  "BLW GHANA ZONE D",
  "BLW Ireland Zone",
  "BLW KENYA ZONE",
  "BLW KENYA ZONE B",
  "BLW Middle East & North  Africa",
  "BLW Namibia Group",
  "BLW SA ZONE F",
  "BLW SA ZONE G DSP",
  "BLW SOUTH AFRICA ZONE A",
  "BLW SOUTH AFRICA ZONE B",
  "BLW SOUTH AFRICA ZONE C",
  "BLW SOUTH AFRICA ZONE D",
  "BLW SOUTH AFRICA ZONE E",
  "BLW South Africa Zone H",
  "Blw South Africa Zone I",
  "BLW TANZANIA ZONE",
  "BLW Uganda Zone",
  "BLW UGANDA ZONE B",
  "BLW UK Sub Zone C",
  "BLW UK SUBZONE C",
  "BLW UK ZONE A",
  "BLW UK ZONE B",
  "BLW UK Zone C",
  "BLW USA GROUP 1",
  "BLW USA GROUP 2",
  "BLW USA Region 1",
  "BLW USA Region 1-updated",
  "BLW USA REGION 1 ZONE B",
  "BLW USA Region 2",
  "BLW USA REGION 2 ZONE B",
  "BLW WALES",
  "BLW ZONE A",
  "BLW ZONE B",
  "BLW ZONE C",
  "BLW ZONE D",
  "BLW ZONE E",
  "BLW ZONE F",
  "BLW ZONE G ",
  "BLW ZONE H",
  "BLW ZONE I",
  "BLW ZONE J",
  "BLW ZONE K",
  "BLW ZONE L",
  "BLW ZONE M",
  "BLW ZONE N",
  "BLW INTERNATIONAL CHAPTERS",
  "C.E AMSTERDAM",
  "C.E KENYA SUB ZONE A",
  "C.E KENYA SUB ZONE B",
  "Calabar Ministry Centre",
  "Cameroon Group 1",
  "Cameroon Group 2",
  "CAMPUS MINISTRY",
  "Cape Town Zone 1",
  "Cape Town Zone 2",
  "CHAD Zone",
  "Christ Embassy Barking DSP",
  "Durban Zone, South Africa",
  "EAST ASIA REGION",
  "Eastern Europe Region",
  "Edo North & Central Zone",
  "Ethiopia Group 1",
  "Ethiopia Group 2",
  "EWCA Zone 1",
  "EWCA Zone 2",
  "EWCA Zone 3",
  "EWCA Zone 4",
  "EWCA Zone 5",
  "EWCA Zone 6",
  "Ghana Zone B",
  "Gombe Sub Zone",
  "Ibadan Zone 1",
  "IBADAN ZONE 2",
  "India Zone",
  "India Zone 2",
  "International Missions for South East Asia",
  "Ireland Sub Zone 2, Region 2",
  "Katsina Sub Zone",
  "Kenya Zone",
  "KOGI SUB ZONE",
  "Lafia Sub Zone",
  "Lagos Sub Zone A",
  "Lagos Sub Zone B",
  "Lagos Sub Zone C",
  "Lagos Sub Zone D",
  "Lagos Virtual Zone",
  "Lagos Zone 1",
  "Lagos Zone 2",
  "Lagos Zone 3",
  "Lagos Zone 4",
  "Lagos Zone 5",
  "Lagos Zone 6",
  "Loveworld Church Zone",
  "Loveworld Global Fellowship",
  "Maiduguri Sub Zone",
  "Middle East & South East Asia Region",
  "Midwest Zone",
  "MINISTRY CENTER IBADAN",
  "Niger Sub Zone, Nigeria",
  "Nigeria North Central Zone 1",
  "Nigeria North Central Zone 2",
  "Nigeria South West Zone 4",
  "Nigeria South West Zone 5",
  "NNE Zone 1",
  "NNW Zone 1",
  "NNW Zone 2",
  "NSE Zone 1",
  "NSE Zone 3",
  "NSS Zone 1",
  "NSS Zone 2",
  "NSS Zone 3",
  "NSW Zone 1",
  "NSW Zone 2",
  "NSW Zone 3",
  "Onitsha Zone",
  "Ottawa Zone, Canada",
  "Port Harcourt Zone 1",
  "Port Harcourt Zone 2",
  "Port Harcourt Zone 3",
  "Quebec Zone",
  "South America Region",
  "SOUTH EAST ASIA INTERNATIONAL",
  "Southern Africa Zone 1",
  "Southern Africa Zone 2",
  "Southern Africa Zone 3",
  "Southern Africa Zone 4",
  "Southern Africa Zone 5",
  "Taraba Sub Zone",
  "Toronto Zone",
  "UK Zone 1, DSP Region",
  "UK Zone 1, Region 2",
  "UK Zone 2, DSP Region",
  "UK Zone 3, DSP Region",
  "UK Zone 3, Region 2",
  "UK Zone 4, DSP Region",
  "UK Zone 4, Region 2",
  "USA Dallas Zone",
  "USA GROUP 4",
  "USA Region 2",
  "USA Region 3",
  "USA Zone 1, Region 1",
  "USA Zone 2, Region 1",
  "Warri DSC Sub Zone",
  "Warri Ministry Centre",
  "Western Europe Zone 1",
  "Western Europe Zone 2",
  "Western Europe Zone 3",
  "Western Europe Zone 4",
];
